### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by FrancescoAriano** [LiquidRemix/android_packages_apps_LiquidLounge#28]
I'm having the following error, someone can fix it? 
[ 70% 62767/89506] AAPT2 compile /home/taniamariabento095/liquid/out/target/product/hero2lte/obj/APPS/Settings_interm...es/packages/apps/LiquidLounge/res/values-it_strings.arsc.flat <- packages/apps/LiquidLounge/res/values-it/strings.xml FAILED: /home/taniamariabento095/liquid/out/target/product/hero2lte/obj/APPS/Settings_intermediates/flat-res/packages/apps/LiquidLounge/res/values-it_strings.arsc.flat /bin/bash -c "/home/taniamariabento095/liquid/out/host/linux-x86/bin/aapt2 compile -o /home/taniamariabento095/liquid/out/target/product/hero2lte/obj/APPS/Settings_intermediates/flat-res/packages/apps/LiquidLounge/res/ --pseudo-localize --legacy packages/apps/LiquidLounge/res/values-it/strings.xml" aapt2 F 06-01 13:36:59 23126 23126 ResourceParser.cpp:257] Check failed: span_stack.empty() spans haven't been fully processed Aborted (core dumped)

**Comment by rrajesh011** [comment]
@francitato u still have issue? all source related error have been fixed, u can compile it.
